# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd16b0e3a43b87fbac9015272213291e718f5e618bb2c0f5b714187d5b2a6dc2ad564a8d345d9c7284f48cf1b1ea68f50ba2d83a5a468c4b14d02db9879d904a

test:
  secret_key_base: 9dd89e11177f12dc2cb720e156b72897a3aaf338c564b2e39089d72f0ba075aa43acdba86e4910f474a4ede767522574595a3e5dbb0b3c8cf79c05059114bf5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
